version: '3.8'
services:
  app:
    image: node:20-alpine
    command: sh -c "npm install && npm run start"
    container_name: server_social
    ports:
      - '3001:3001'
    working_dir: /app
    volumes:
      - ./.:/app
    environment:
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DB: social_db

  postgres:
    image: postgres:latest
    container_name: social_db
    ports:
      - '5432:5432'
    environment:
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DB: social_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local
