services:
  app:
    image: node:20-alpine
    command: sh -c "npm install && npm run start"
    container_name: server_social
    ports:
      - '3001:3001'
    working_dir: /app
    volumes:
      - ./.:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_db
      REDIS_URL: redis://redis_cache:6379
    depends_on:
      - postgres
      - redis_cache

  postgres:
    image: postgres:latest
    container_name: social_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis_cache:
    image: redis:latest
    container_name: social_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - 'cache:/data'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: social_elasticsearch
    environment:
      - node.name=social_node
      - cluster.name=social_cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: social_kibana
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  beanstalkd:
    image: schickling/beanstalkd
    container_name: social_beanstalkd
    ports:
      - '11300:11300'
    volumes:
      - beanstalkd_data:/var/lib/beanstald

  jaeger:
    image: jaegertracing/jaeger:2.0.0
    ports:
      - '16686:16686' # UI
      - '14268:14268' # HTTP endpoint for OpenTelemetry
      - '14250:14250' # gRPC
      - '6831:6831/udp' # UDP (agent Thrift)
      - '5778:5778' # config for agents
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

volumes:
  pgdata:
    driver: local
  cache:
    driver: local
  esdata:
    driver: local
  beanstalkd_data:
    driver: local
